### ISSUE TITLE
Recipes dont work on Single player and multiplayer world 

### ISSUE THREAD

**Issue by Khotyz** [LordDeatHunter/Alloy-Forgery#10]
hello, i'm curseforge's uPyke, and i'm here so i can post the modlist i use to play minecraft where there is a bug of not showing alloy forgery recipes in single player, so go below to the list of mods i use where it occurs the bug

<details>
  <summary>Mod List</summary>
  
   [1.16.4]+MoreTooltips-1.0.1.jar"
 adapaxels-1.0.7+1.16.5.jar"
 adventurez-1.2.2.jar"
 Allure-1.2.8.jar"
 animal_feeding_trough-1.0.2.jar"
 appleskin-mc1.16-fabric-1.0.11.jar"
 artifacts-3.2.1+fabric.jar"
 backslot-1.1.11.jar"
 bambootweaks-2.0.1+1.16.5.jar"
 beach-slimes-2.1.0+mc1.16.1.jar"
 BeaconOverhaul-1.3.1+1.16.jar"
 betterdroppeditems-1.2.4-1.16.2.jar"
 BetterMineshafts-Fabric-1.16.4-1.0.1.jar"
 BetterPingDisplay-Fabric-1.16.4-1.1.jar"
 bettersleeping-0.4.0.jar"
 BetterStrongholds-Fabric-1.16.5-1.0.jar"
 betterthanmending-1.3.0.jar"
 BetterThirdPerson-Fabric-1.16.4-1.4.0.jar"
 biome_locator-1.1.2.jar"
 biome-makeover-1.16.5-1.3.8.jar"
 byg-1.1.8.jar"
 campanion-1.3.5.jar"
 carrier-1.7.6.jar"
 cavebiomes-0.6.2.jar"
 charm-fabric-1.16.5-2.3.2.jar"
 cherishedworlds-fabric-1.3.0-1.16.4.jar"
 chillager_mod-1.1.jar"
 cinderscapes-1.3.3.jar"
 CleanView-1.16.5-v1-fabric.jar"
 cloth-config-4.11.26-fabric.jar"
 comforts-fabric-0.0.3-1.16.5.jar"
 consistency_plus-0.3.0.jar"
 Controlling-For-Fabric-1.1.3.jar"
 cosmetic-armor-1.0.0.jar"
 Couplings-1.3.6.jar"
 CraftPresence-Fabric-1.16.5-Release-1.8.1.jar"
 crimson-moon-2.0.4-1.16.5.jar"
 curioofundying-fabric-1.1.1-1.16.5.jar"
 curios-fabric-0.0.13-1.16.5.jar"
 DamageTilt-1.16-fabric-0.1.2.jar"
 DarkDungeons-0.1.1.jar"
 dark-loading-screen-1.6.3.jar"
 deep-dungeons-1.0.0-1.16.5.jar"
 diggusmaximus-1.4.2-1.16.3.jar"
 DisableCustomWorldsAdvice-1.2.jar"
 DualRiders-1.0.5.jar"
 DungeonsModLite-1.16.5-1.0.5.jar"
 DynamicSoundFilters-1.2.0+1.16.5.jar"
 Earth2Java-1.7.1+1.16.4.jar"
 eldritch-mobs-1.7.0.jar"
 EmeraldTools-Fabric-1.16.5-1.1.3.jar"
 EnchantmentDescriptions-fabric-1.16.5-2.0.4.jar"
 fabric-api-0.34.2+1.16.jar"
 fabric-furnaces-1.3.3-1.16.4.jar"
 fabric-language-kotlin-1.6.0+kotlin.1.5.0.jar"
 fabric-pigsteel-mod-1.4.0.jar"
 fallingleaves-1.6.0+1.16.5.jar"
 fatxporbs-0.0.9+1.16.4.jar"
 flytre_lib-0.2.10.jar"
 gate-of-babylon-1.4.3-1.16.5.jar"
 gildedarmor-1.16.5-1.1.0.jar"
 give-me-hats-1.16-1.5.1.jar"
 glassdoor-1.5.0-1.16.jar"
 glassential-fabric-1.16.4-1.1.5.jar"
 goldensteak-1.0.2.jar"
 Harvest-fabric-1.16.1-1.2.12-26.jar"
 HealthOverlay-1.16.4-3.6.14.jar"
 horse-stats-vanilla-4.1.8.jar"
 hypnos-0.1.2.jar"
 illuminations-1.5.1.jar"
 IronChest-1.2+fabric-1.16.4.jar"
 jumpoverfences-1.16-0.0.3.jar"
 kibe-1.16.5-1.6.9-BETA.jar"
 kiln-1.1.1+1.16.5.jar"
 leaf-decay-1.2.0-1.16.1.jar"
 libblockattributes-all-0.8.8.jar"
 lithium-fabric-mc1.16.5-0.6.4.jar"
 mcda-1.4.5.jar"
 mcdar-1.1.2.jar"
 mcdw-3.1.5.jar"
 medievalweapons-1.1.1.jar"
 modmenu-1.16.9.jar"
 Monster-of-the-ocean-depths-3.1-1.16.5.jar"
 monsters-in-the-closet-1.0.0+1.16.jar"
 MoreGems-Fabric_1.16.5-1.1.22.jar"
 more-totems-mod-2.7.3.jar"
 mostructures-1.1.1+mc.1.16.5.jar"
 mythicmetals-0.9.9.jar"
 NamePain-1.3.1+Fabric-1.16.x.jar"
 nourish-1.2.1.jar"
 okzoomer-4.0.1+1.16.2.jar"
 overworld-two-1.0.4.jar"
 packages-1.16.4-1.1.1.jar"
 Pal-1.2.2.jar"
 Patchouli-1.16.4-51-FABRIC.jar"
 Pehkui-2.1.0+21w18a.jar"
 phosphor-fabric-mc1.16.3-0.7.2+build.12.jar"
 piglib-1.0.3+1.16.5.jar"
 polymorph-fabric-0.0.10-1.16.5.jar"
 rer-2.1.3.jar"
 reroll-1.2.1-1.16.5.jar"
 RingsOfAscension-1.16.4-1.1.1.jar"
 riverredux-0.1.6.jar"
 RoughlyEnoughItems-5.11.202.jar"
 rpgstats-4.0.3+1.16.5.jar"
 SaveMyStronghold-Fabric-1.16.4-1.0.jar"
 seamless-loading-screen-1.3.4+1.16.2.jar"
 seasons-1.16.5-1.2-BETA.jar"
 secretrooms-0.9.5+1.16.5.jar"
 SimpleBackpack_Fabric_1.16.5-1.0.38.jar"
 simpledrawers-1.8.0-1.16.3.jar"
 simpleteleporters-2.2.1.jar"
 smoothboot-fabric-1.16.5-1.6.0.jar"
 sodium-extra-0.3.0.jar"
 sodium-fabric-mc1.16.3-0.1.0.jar"
 spark-fabric.jar"
 staffofbuilding-1.2.6-1.16.5.jar"
 stoneholm-1.2.1.jar"
 strawdummy-1.4.0.jar"
 SurvivalAdditions-1.3.2-Fabric-1.16.5.jar"
 terrestria-2.2.0.jar"
 things-0.1.2.jar"
 tomsstorage-1.1.10.jar"
 torohealth-1.16.4-fabric-4.jar"
 trapexpansion-1.16.2-1.3.3.jar"
 traverse-3.3.2.jar"
 trinkets-2.6.7.jar"
 vafoen1.1.1+1.16.5.jar"
 vanilladeathchest-1.16.3-1.11.0.7-fabric.jar"
 vanillaexcavators-2.1.2-1.16.2.jar"
 vanilla-hammers-3.0.3-1.16.5.jar"
 WoodsAndMires-1.0.4+1.16.3.jar"
 wraith-alloy_forgery-1.2.0.jar"
 wraith-harvestscythes-2.0.4.jar"
 wraith-waystones-1.1.1.1.jar"
 Xaeros_Minimap_21.8.2_Fabric_1.16.5.jar"
 XaerosWorldMap_1.14.0_Fabric_1.16.5.jar"
 YungsApi-1.16.5-Fabric-5.jar"
  
</details>

**Comment by Noaaan** [comment]
This is a really hefty modlist to go though, just downloading all of these mods will take some time.
I will try to provide a test build which will help out in solving this issue

**Comment by Khotyz** [comment]
no problem and sorry for delay, i can upload my mods folder with all of them, here is the link: https://drive.google.com/file/d/18N843iF77Nba_M7dOD9lSj6SdVvVHmQW/view?usp=sharing 😊

**Comment by Noaaan** [comment]
I have re-discovered this issue. It was reported a while back in the Wraith Discord, as it is related to Charm.
I opened an issue (https://github.com/svenhjol/Charm/issues/511) back in march, but it has not gotten any responses yet. I am looking into alternate ways of doing recipes, but for now I can only recommend trying to disable modules of Charm related to recipes, or just disable it entirely.
