### ISSUE TITLE
crash game, pls help

### ISSUE THREAD

**Issue by OneDayGame435** [LordDeatHunter/Alloy-Forgery#100]
My friend try to play with us in minecraft 1.19.2 on fabric 14.14, but his game crashed if anybody drob item. Pls help me and my friend with it. <3
[crash-2023-03-26_18.17.20-client.txt](https://github.com/wisp-forest/alloy-forgery/files/11071081/crash-2023-03-26_18.17.20-client.txt)
[crash-2023-03-26_18.12.58-client.txt](https://github.com/wisp-forest/alloy-forgery/files/11071085/crash-2023-03-26_18.12.58-client.txt)
[crash-2023-03-26_18.11.16-client.txt](https://github.com/wisp-forest/alloy-forgery/files/11071086/crash-2023-03-26_18.11.16-client.txt)

**Comment by gliscowo** [comment]
What made you conclude that this issue is related to Alloy Forgery? 

None of the crash reports you sent mention Alloy Forgery at all, they rather put the blame on DropLight or Porting Lib (used by mods like Create Refabricated)

**Comment by gliscowo** [comment]
As this is is both stale and seemingly completely unrelated to Alloy Forgery, I'll be closing it. If you have more to say, feel free to comment again and potentially re-open it

Cheers
