### ISSUE TITLE
KubeJS Scripts Won't Load With Alloy Forgery on 1.19.2

### ISSUE THREAD

**Issue by muhammedesadcomert** [LordDeatHunter/Alloy-Forgery#102]
Minecraft: 1.19.2
Fabric: 0.14.17
Fabric API: 0.76.0+1.19.2
KubeJS: 1902.6.0-build.142
Alloy Forgery: 2.0.19+1.19

KubeJS Script Log: https://mclo.gs/ty2Nu98#L392

**Comment by Noaaan** [comment]
Duplicate of #98, the fix is already available for latest Alloy Forgery (2.0.19+1.19.4, marked as beta/pre-release)
There are currently no plans to backport it to 1.19.2.

**Comment by muhammedesadcomert** [comment]
I changed the title. So, you should pin this issue for other players facing this issue instead of closing it. This way you can avoid duplicates.
