### ISSUE TITLE
[Feature Request] Support KubeJS

### ISSUE THREAD

**Issue by EvanHsieh0415** [LordDeatHunter/Alloy-Forgery#106]
like
```js
ServerEvents.recipes(event => {
    event.recipes.alloyForgery.forging(
        { // Output
            priority: Array, // if ${default} isn't tag: Optional, default: [${default}]
            default: String,
            count: Number // Optional, default: 1
        },
        [ // Input[]
            Item / Ingredient,
            ...
        ]
    ).overrides(Object) // Optional, default: {}
    .minForgeTier(Number) // Optional, default: 1
    .fuelPerTick(Number) // Optional, default: 5
})
```

**Comment by Dragon-Seeker** [comment]
I really don't understand the need here. Dosn't KubeJS allow for JSON Injection for custom recipes? Why add support for something that will be required to maintain compatibility and a feature used as a Fancyer wrapper than custom? 

More info on what your requesting and the reason for such would allow for better evaluation of this.

**Comment by EvanHsieh0415** [comment]
First of all, I apologize for my previous use of "require". I'm not very familiar with English, which caused me to use the wrong vocabulary.

Furthermore, this mod is suitable for modifying recipes in modpacks, and if it supports KubeJS, it can improve development efficiency. However, if modpack developers use event.custom built into KubeJS, it will make the code redundant and difficult to maintain.

**Comment by EvanHsieh0415** [comment]
By the way, I have now written a recipe builder using JavaScript.

![image](https://user-images.githubusercontent.com/74277414/235270521-3eafbbfa-5ba0-4666-8141-e7a6ddf43ac0.png)

**Comment by gliscowo** [comment]
Given that Alloy Forgery recipes are already perfectly usable using just standard KubeJS features, we won't be implementing and thus maintaining any specific support.

Cheers

**Comment by EvanHsieh0415** [comment]
Although I do not think it is perfectly, but since the author does not intend to produce, but so be it
