### ISSUE TITLE
[Question] Is it possible to disable default recipes?

### ISSUE THREAD

**Issue by N3aar** [LordDeatHunter/Alloy-Forgery#109]
I noticed that there are some recipes by default, wanted to be able to change these recipes without duplicating them, is it possible?
sorry if this information already exists somewhere, I couldn't find it on the Wiki

**Comment by gliscowo** [comment]
All you need to do is to place your recipes in the `alloy_forgery` namespace in your datapack and give them the same name as the ones in Alloy Forgery - that should override them just fine

Feel free to ask back if you have more questions
Cheers
