### ISSUE TITLE
Alloy Forge does not work with hoppers/pipes

### ISSUE THREAD

**Issue by MUHAKLorTheDorfTrottel4Github** [LordDeatHunter/Alloy-Forgery#11]
Mc 1.17
fabric-api-0.34.9+1.17.jar
wraith-alloy_forgery-1.3.0.jar

Forgery does NOT:
give any experience
react on hoppers or pipes/ducts

regards

**Comment by Noaaan** [comment]
The Alloy Forge originally was not planned to give any experience, as this would be the trade-off for getting a higher output (1.5x output from normal ores).
Regarding pipes and hoppers this is something we are looking into. We do want to add some sort of side interface, or use some other solution for the forge.
