### ISSUE TITLE
Causing Launcher To Not Work

### ISSUE THREAD

**Issue by GamesBeatGamer** [LordDeatHunter/Alloy-Forgery#110]
I downloaded this mod and added it to my mod folder (Fabric) and every time i launch the game it loads a little bit then closes the launcher and doesn't open the game

**Comment by gliscowo** [comment]
You need to give us more context if we want to even try to debug this problem. Please send us your `latest.log` file from a time when this issue occured

Cheers

**Comment by gliscowo** [comment]
Given that this issue has now been stale for almost 2 months, I'll go ahead and close it. If you still think the problem is relevant, feel free to provide the required information and reopen it

Cheers
