### ISSUE TITLE
[Bug] Possible Incompatibility with Enhanced Celestials

### ISSUE THREAD

**Issue by Ultimushadow** [LordDeatHunter/Alloy-Forgery#115]
Hi there, I'm getting the attached crash report every time I load up a world with both Enhanced Celestials and Alloy Forgery loaded.
I'm playing on 1.20.1 Fabric, relevant mods are:
 - CorgiLib 4.0.0.4
 - Enhanced Celestials 5.0.0.2
 - owo 0.11.1
 - Alloy Forgery 2.0.22

When I disable Alloy Forgery, the world can load. This applies to worlds made before and after installing Alloy Forgery.
Game also loads with Alloy Forgery and without Enhanced Celestials.

I've made an issue report with EC here: https://github.com/CorgiTaco/Enhanced-Celestials/issues/174

**Comment by Dragon-Seeker** [comment]
Ngl this issue seems similar to this one https://github.com/CorgiTaco/Enhanced-Celestials/issues/171 and most likely is due to AF using something with Fabric API that leads to the mod crashing.

**Comment by Dragon-Seeker** [comment]
This seems to be an issue with Enhanced Celestials and until more information, I am closing this unless such contradicts such a thought.
