### ISSUE TITLE
[Bug] Crash with BigGlobe

### ISSUE THREAD

**Issue by Martmists-GH** [LordDeatHunter/Alloy-Forgery#118]
See also: https://github.com/Builderb0y/BigGlobe/issues/2

Log: https://mclo.gs/ldKIjeL

**Comment by BasiqueEvangelist** [comment]
Does this happen with just owo-lib, or does alloy forgery also need to be installed?

**Comment by Martmists-GH** [comment]
owo-lib on its own is fine, alloy forgery triggers the crash.

**Comment by Builderb0y** [comment]
(Developer of big globe here) This is a race condition. Something is class loading fabric's DynamicRegistriesImpl class before big globe added its own entries to the vanilla DYNAMIC_REGISTRIES field. Not strictly alloy forgery's fault. This will probably happen with any mod which uses fabric's dynamic registries API. I am working on a fix now.

**Comment by Builderb0y** [comment]
It's been 3 days since I released my fix and I have yet to hear any new complaints, so I'm going to assume my fix works. This issue can probably be closed now.
