### ISSUE TITLE
Hoppers won't take things out of the forge

### ISSUE THREAD

**Issue by mcheezic05** [LordDeatHunter/Alloy-Forgery#120]
Title says it all. I try putting a hopper under the block like it shows on the wiki and nothing happens.

**Comment by Noaaan** [comment]
Both of the methods in the added image below works. Tested with Alloy Forgery 2.0.21
If this is not the case for you, could you provide more details on your modded context? A log would suffice, as it contains your entire mod list, as well as any errors which could be relevant. 

![image](https://github.com/wisp-forest/alloy-forgery/assets/4163353/f0b4d5da-88b1-4f8e-b8d7-850f557769df)

**Comment by mcheezic05** [comment]
Had no idea that the hopper directly under the controller was valid. That works, though strangely enough the second one still doesn't. Here's the most recent log file, hopefully that helps.
[2023-12-01-4.log](https://github.com/wisp-forest/alloy-forgery/files/13533746/2023-12-01-4.log)

**Comment by Nereithr** [comment]
Cannot reproduce on Fabric 1.20.1 with any of the available mod versions. 

*Can* reproduce this on NeoForge 1.20.1 with Sinytra Connector, so I'm assuming it's on their end and I filed an issue there.
