### ISSUE TITLE
Server Crash when using forge (Ticking entity) 1.20.1

### ISSUE THREAD

**Issue by BeefyBressler** [LordDeatHunter/Alloy-Forgery#122]
[crash-2023-12-01_22.58.20-server.txt](https://github.com/wisp-forest/alloy-forgery/files/13532560/crash-2023-12-01_22.58.20-server.txt)

**Comment by Dragon-Seeker** [comment]
Fixed as of the latest release version of Alloy Forgery: https://modrinth.com/mod/alloy-forgery/version/2.1.1+1.20
