### ISSUE TITLE
Duplicate item stack added to creative tab causing a crash

### ISSUE THREAD

**Issue by sleepy-evelyn** [LordDeatHunter/Alloy-Forgery#124]
**To replicate**: Open the creative mod inventory. It weirdly doesn't crash all the time. It was working for a fair while. Idk if I did something to trigger it. Maybe a resource reload?

**Crash log**: https://gist.github.com/sleepy-evelyn/dfbbb371598934808c88295f4d5e54d5

**Modpack**: https://modrinth.com/modpack/stitched (Stitched Extras 0.2.0-beta)

**Comment by sleepy-evelyn** [comment]
Another thing to note is i'm using Spectrum which adds Alloy Forgery Compatibility and it's own tab entries. It may be an issue with that. The reason i'm not reporting on Spectrum yet though is it shows an issue with the Deepslate Controller only atm.

It also doesn't seem to break initially after a datapack reload or a resource pack reload.

**Comment by Dragon-Seeker** [comment]
Overall having a hard time replicating this crash at all. I don't know exactly how much could be happening based on the code being used. Combined with the crash log not indicate how the problem is occurring so it is really hard to investigate further.

**Comment by Dragon-Seeker** [comment]
Due to the Quilt platform causing issues that are hard to reproduce, this issue will be closed and support for such is not on the tables.

**Comment by sleepy-evelyn** [comment]
> Due to the Quilt platform causing issues that are hard to reproduce, this issue will be closed and support for such is not on the tables.

It never is an issue directly with Quilt I have no idea why developers keep doing this lol. Unless it's a Quilt specific mod then it will be an issue with Fabric or more importantly Quilts replica of Fabrics API which is mostly identical.

Out of all the 100s of issues i've submitted i've had least 10+ say it's related to Quilt and it never is
