### ISSUE TITLE
Datapack Fuels is causing fuels not to be used

### ISSUE THREAD

**Issue by TheWyzer** [LordDeatHunter/Alloy-Forgery#127]
MC 1.20.1
Fabric
Modpack: Quantum Freedom 2 
Added additional mods

I created a datapack per your extremely helpful guide in your wiki.

I wanted to add Lignite coal as a fuel.  I can place the new fuel and any other standard fuel on the forge, however they are not consumed/use, and no ingot is made.

Below is the fuels.json I created in the "alloy_forge.zip" and the fuels.json is in /data/alloy_forge/alloy_forge_fuels/ folder, as per the wiki.  I have removed everything but minecraft coal, and if the datapack is used, it simply will not allow fuel to be consumed/ingots to be made.

Here is the fuels.json file;

```
{
  "fuels": [
    {
      "item": "minecraft:lava_bucket",
      "return_item": "minecraft:bucket",
      "fuel": 24000
    },
    {
      "item": "minecraft:coal",
      "fuel": 10000
    },
    {
      "item": "minecraft:charcoal",
      "fuel": 10000
    },
    {
      "item": "minecraft:blaze_rod",
      "fuel": 20000
    },
    {
      "item": "minecraft:coal_block",
      "fuel": 90000
    },
    {
      "item": "modern_industrialization:lignite_coal",
      "fuel": 10000
    },
    {
      "item": "modern_industrialization:lignite_coal_block",
      "fuel": 90000
    }
  ]
}            
```            
I did make a mistake where I forgot to add the coma at the end of the new items, the log pointed me to the line issue, so I corrected it.  I have just a direct copy from your wiki, and even removed all the items except minecraft:coal.  I can put the fuel in the fuel spot, it simply won't be consumed (generate heat) and produce ingots.

If I remove the datapack the forge works properly, with the minecraft coal/coal blocks.

Is there something else I am missing?

**Comment by Noaaan** [comment]
Are you still experiencing this issue? I recently tested this but was not able to reproduce this

**Comment by TheWyzer** [comment]
Actually I just figured out that I can change the order of how the mod load.  So I just ensure that your mod is loaded AFTER the GAC mod.  It works for me now.  Thank you for checking.

**Comment by TheWyzer** [comment]
I have not used the datapack for nearly 6 months, and I believe I deleted the instance that I was using this pack on.
