### ISSUE TITLE
Enhancement: Smelt stone and other blocks in forgery.

### ISSUE THREAD

**Issue by jimmytrouser** [LordDeatHunter/Alloy-Forgery#130]
Would be great to be able to smelt stone and other blocks in forgery.

Maybe this can be done in cfg files?

Thanks.

**Comment by Noaaan** [comment]
As Alloy Forgery in concept is an enhanced Blast Furnace this is not something a recipe we are particularily considering adding at this time. 
If you want to create something for yourself to be able to add recipes, this is entirely possible! This requires making a small datapack. There are many tutorials online on how to do this, and we do provide some documentation ourselves on how to do such:
https://docs.wispforest.io/datapack-tutorial/
https://docs.wispforest.io/alloy-forgery/home/
