### ISSUE TITLE
Modded Blocks on Datapack Furnace

### ISSUE THREAD

**Issue by ItoKyoshiro** [LordDeatHunter/Alloy-Forgery#131]
Hi! I tested it using Synnitra on Forge, so if this is not on your end it would be nice to know so I can report under the Connector guys :D (but I posted it here first because I don't think the block registration change between loaders)

I noticed that the mod don't recognize the Create Modded Blocks when adding them into "additional_materials" for Furnace Datapack.
Didn't tested with the main "material" but would guess the same behavior.

Here you can check the file, just in case
[deepslate_bricks_forge.json](https://github.com/wisp-forest/alloy-forgery/files/14981142/deepslate_bricks_forge.json)

**Comment by Noaaan** [comment]
This is just a link to the default file. What did you actually add to it?

**Comment by ItoKyoshiro** [comment]
I added the Cracked version (Minecraft) and the Cut and Small Deepslate versions from Create

**Comment by Noaaan** [comment]
I think I am going to close this issue for now, as it seems very related to datapacking. There are many other resources online on how to make one, and we provide documentation on how to use our format here:
https://docs.wispforest.io/alloy-forgery/home/
