### ISSUE TITLE
(Suggestion) Allow Fluids as Output

### ISSUE THREAD

**Issue by ItoKyoshiro** [LordDeatHunter/Alloy-Forgery#132]
Hey! I don't know how hard it is to implement, but would be really cool to have the option to get liquid as output so it can interact better with other mods

**Comment by Noaaan** [comment]
The idea is really cool in principle, but generally it is very out of scope with Alloy Forgery. For this in particular there are already alternatives available, like Tinkers Construct 3 (Forge) or Hephaestus (Fabric). If we wanted to make this it would serve as an addon, as it would generally require a lot more multiblock modularity to be useful.
