### ISSUE TITLE
Invalid Multiblock Configuration

### ISSUE THREAD

**Issue by Kerem124523** [LordDeatHunter/Alloy-Forgery#134]
As soon as i right click the block the forge controller it says invalid multiblock configuration and i cant do anything with the block and it becomes useless

**Comment by pepzp** [comment]
i got the same problem

**Comment by Noaaan** [comment]
![image](https://github.com/wisp-forest/alloy-forgery/assets/4163353/7798188a-31fa-42dd-98a6-23ed96d211d2)
