### ISSUE TITLE
[Feature Request] JEI Compatability

### ISSUE THREAD

**Issue by Noaaan** [LordDeatHunter/Alloy-Forgery#137]
Supersedes https://github.com/Noaaan/MythicMetals/issues/217

While not strictly necessary, adding JEI compat to Alloy Forgery could be beneficial. It would reduce maintenance by not requiring the EMI plugin, since you can use it via EMI's JEI compat layer

**Comment by Dragon-Seeker** [comment]
I am frankly against adding support for JEI replacing EMI as I would rather have REI and EMI in all cases combined with the fact that both REI(Forge Only If I remember correctly) and EMI have compatibility layers to handle JEI mods meaning there is no need to touch such.

Combined with a little talk from @gliscowo it would just push the maintenance cost to have a JEI plugin instead to target more inclusivity but frankly, JEI's tech debt and lack of features make such seem like a worse replacement to suit people who have yet to switch to better options in general.
