### ISSUE TITLE
[Feature Request] Compatibility with the mod called Bronze by June.

### ISSUE THREAD

**Issue by makumaku1974** [LordDeatHunter/Alloy-Forgery#138]
The Bronze mod adds two things which is Tin and Bronze.

**Comment by khazoda** [comment]
I will work on compatibility with alloy forgery, thanks for the request!

**Comment by khazoda** [comment]
Compatibility added in version 1.0.8+1.21 [Modrinth](https://modrinth.com/mod/bronze/version/1.0.8+1.21)
PR: https://github.com/Khazoda/bronze/pull/10
