### ISSUE TITLE
Alloy Forgery 2.2.1 failing to load

### ISSUE THREAD

**Issue by Gamemassa** [LordDeatHunter/Alloy-Forgery#142]
Minecraft 1.21
Fabric Loader 0.16.0
Fabric API 0.100.7
Alloy Forgery 2.2.1

Hi, I added the latest version of alloy forgery to my custom modpack (because Mythic Metals requires it) and got an error that said "Errors in the currently selected datapacks prevented the world from loading." My game didn't actually crash, so I don't have a crash report, but I have attached the latest.log in case that helps. Also, I did look at #139 before posting this, and it looks similar but not completely related.

Latest.log:
https://mclo.gs/EmiMDAD

**Comment by Noaaan** [comment]
I think I see why this issue occurs. A fix will be available ASAP

**Comment by Noaaan** [comment]
Should be fixed as of 2.2.2, which just released :+1:

**Comment by Gamemassa** [comment]
> Should be fixed as of 2.2.2, which just released 👍

Tested and confirmed. It's definitely working now. What was causing the issue, out of curiosity?

**Comment by Noaaan** [comment]
You can see the change in the commit reference above. Essentially Fabric API have had their resource conditions updated for a while, and our manual compat recipes were using the old format. The old format didn't work, so they loaded despite being invalid
