### ISSUE TITLE
Incompatibility with Remove Reloading Screen?

### ISSUE THREAD

**Issue by ZannCoelz** [LordDeatHunter/Alloy-Forgery#143]
In my previous issue #139 there was a lot of discussion about the crash having to do with Remove Reloading Screen. I was testing this and it seems to be as they said. This issue still happens to me in version 2.2.2 so I decided to report it separately. This issue happens when entering singleplayer world creation screen.

Here are some crashreports that I got. I reproduced this 3 times and got a bit different crashreport each time (They are all really similar to #139 crashreport):
[crash-2024-07-19_13.59.00-client.txt](https://github.com/user-attachments/files/16311077/crash-2024-07-19_13.59.00-client.txt)
[crash-2024-07-19_14.00.59-client.txt](https://github.com/user-attachments/files/16311078/crash-2024-07-19_14.00.59-client.txt)
[crash-2024-07-19_13.40.58-client.txt](https://github.com/user-attachments/files/16311079/crash-2024-07-19_13.40.58-client.txt)

( Sorry for again reporting the same or at least a very similar issue :/ )

**Comment by Noaaan** [comment]
Could you provide a full log? Previously the recipes failing was present there, and as such it was really easy to identifiy the issue

**Comment by ZannCoelz** [comment]
Sure!

Here it's:
[latest.log](https://github.com/user-attachments/files/16311898/latest.log)

**Comment by Noaaan** [comment]
I believe this assumption is correct. There is something that Remove Reloading Screen does that seems to break Fabrics Resource Conditions. I suggest reporting this to their repository

**Comment by ZannCoelz** [comment]
I'll do that. Thanks for looking into it!

**Comment by ZannCoelz** [comment]
They fixed the issue with their latest update. Thanks again for the help here!
