### ISSUE TITLE
Does not melt 1.17 raw ores

### ISSUE THREAD

**Issue by Limkanimka** [LordDeatHunter/Alloy-Forgery#15]
Minecraft: fabric-loader-0.11.6-1.17
fabric-api-0.36.0 1.17
Alloy Forgery 1.3.2

does not melt "raw" ores
for example "raw iron" or "raw gold"

But works with “ores”
for example "iron ore" or "gold ore"

**Comment by Noaaan** [comment]
Are you sure this is the case? I added these recipes last patch. I would recommend deleting your config folder and trying again, as it might have something to do with the new recipes not being added.

**Comment by Limkanimka** [comment]
Removed all mods, cleaned the folder and deleted config

after installed only:
fabric-api-0.36.0 1.17
Alloy Forgery 1.3.2

I went into a single player game, built a blackstone forge and put a stacks of coal there.

Then I put 10 raw iron there:
The melting does not start, the percentage is at 0%

while with normal ore everything is fine and it melts quietly.

![Capture](https://user-images.githubusercontent.com/86749209/124118874-80668600-da7a-11eb-928c-d34ab3721533.PNG)
![Capture1](https://user-images.githubusercontent.com/86749209/124118876-80ff1c80-da7a-11eb-8f02-6db0e37c872e.PNG)

**Comment by Limkanimka** [comment]
I am using github for the first time and I don’t know if I need to open a new "Issue" or I need to write in the one that is already open, but if you build 2 or more stoves and put fuel in 1 stove, for example, a stack of coal, then the filling of the fuel level will be displayed in all stoves ( visual bug).
The same is with melting, the percentage of melting is displayed in all stoves

**Comment by Limkanimka** [comment]
RoughlyEnoughItems-6.0.260-alpha-fabric

Recipes with "raw" are also not displayed in the REI

![Capture](https://user-images.githubusercontent.com/86749209/124124334-fa017280-da80-11eb-8475-14671e04069a.PNG)
![Capture1](https://user-images.githubusercontent.com/86749209/124124343-fc63cc80-da80-11eb-9dfd-36080f7bf16c.PNG)
![Capture2](https://user-images.githubusercontent.com/86749209/124124387-084f8e80-da81-11eb-931d-d90c143001e8.PNG)

**Comment by Noaaan** [comment]
I think its best to split this into separate issues, as they are very different in nature. I will deploy a quick fix for the smelting of raw ores right now, as it is fairly simple. I am aware of the other issues, and they will take some time to be fixed.
