### ISSUE TITLE
Not sure what happened 

### ISSUE THREAD

**Issue by Limkanimka** [LordDeatHunter/Alloy-Forgery#18]
I can't say how it happened

I put 8 ancient debris in the forge
(should have received 12 scrap)
after that I immediately teleported to another place ~30,000 blocks

5 minutes later I returned home, there were still 8 ancient debris in the forge, but at the same time there were 12 scrap at the exit

this is not a visual bug
I still have 8 ancient debris and also 12 scrap.

**Comment by glisco03** [comment]
At this point investigating theses issues is not worth it anymore. I'm currently working on a rewrite that'll basically be a completely new mod with the same features but a majorly different, and arguably better, codebase. I hope all issues will be fixed when that releases in a few days
Cheers
