### ISSUE TITLE
Crash when starting game

### ISSUE THREAD

**Issue by emoace** [LordDeatHunter/Alloy-Forgery#19]
[crash-2021-07-12_00.59.24-client.txt](https://github.com/LordDeatHunter/Alloy-Forgery/files/6798882/crash-2021-07-12_00.59.24-client.txt)

**Comment by Noaaan** [comment]
Thank you for reporting this issue. It appeared due to an outdated version of some libraries for Conjuring. This has been fixed in an upcoming release, so please update it when it comes out.

**Comment by emoace** [comment]
Thank you!  Excited to use these mods in my pack!
