### ISSUE TITLE
[1.16.5] how to add custom recipes? recipes.json resets on startup ...

### ISSUE THREAD

**Issue by MSandro** [LordDeatHunter/Alloy-Forgery#20]
Hi, I am trying to add custom recipes, but if I add something in the recipes.json, it resets on the next game start.
I tried to add the recipe via Datapack too, but nothing happened... any help?

**Comment by MSandro** [comment]
[recipes.json.txt](https://github.com/LordDeatHunter/Alloy-Forgery/files/6809687/recipes.json.txt)
[bronze_ingot.json.txt](https://github.com/LordDeatHunter/Alloy-Forgery/files/6809689/bronze_ingot.json.txt)

**Comment by MSandro** [comment]
![image](https://user-images.githubusercontent.com/10937159/125472950-4c144a25-6c50-45a7-b909-21b8d513ae87.png)
this looks not correct too

**Comment by glisco03** [comment]
Mutiple Questions

- What version of AF are you running?
- What recipe format have you tried? I know there is no documentation for the new version yet, I can write it up if you need it.
- When did that thing in the GUI happen?

**Comment by MSandro** [comment]
Alloy Forgery 1.2.0
here are the files:
> [recipes.json](https://github.com/LordDeatHunter/Alloy-Forgery/files/6809687/recipes.json.txt)
> [bronze_ingot.json](https://github.com/LordDeatHunter/Alloy-Forgery/files/6809689/bronze_ingot.json.txt)

**Comment by MSandro** [comment]
any idea how to solve the recipe issues? I would realy like to use this mod in my Fabric Skyblock Modpack.

**Comment by Noaaan** [comment]
The legacy Alloy Forgery recipe format is completely different from the current iteration. We are still considering whether or not to backport to this version.
I will write a tutorial on the wiki later tonight for legacy versions. I want to note that with the old versions nothing is done through data. Everything is done through the config folder. You can either add stuff using the API in the mod, or just manually add stuff to the config, and ship it with your modpack.

**Comment by MSandro** [comment]
Thanks. I will try to follow the tutorial when you have published it. Maybe I was a bit too stupid to add a recipe with the recipes.json in the config folder...

**Comment by Noaaan** [comment]
https://github.com/LordDeatHunter/Alloy-Forgery/wiki/%5BLegacy---up-to-1.3.2%5D-Defining-Forges,-Materials-and-Recipes
