### ISSUE TITLE
[1.17+] Forges do not process "Raw" materials

### ISSUE THREAD

**Issue by Gazzoo-byte** [LordDeatHunter/Alloy-Forgery#23]
As above, Forges do not recognise/process the new Raw type materials from 1.17+

**Comment by Noaaan** [comment]
Can you provide more details? Please provide the Alloy Forgery version you are using, and a list of your active mods

**Comment by Gazzoo-byte** [comment]
Only mod is Version 2.0.1 of Alloy Forgery.
![image](https://user-images.githubusercontent.com/73721238/128375081-56d7052a-d986-42b0-a297-9a43d4de5e67.png)

The new "Raw Iron" material doesn't get smelted into ingots by the forge

**Comment by Noaaan** [comment]
I recommend installing REI, as it is a very helpful addition for playing modded Minecraft in general. We actively support it.
The recipe is 2 raw iron (one ore in slot 1, and one in slot 2) for 3 ingots. This increases to 4 ingots with a forge of tier 2 or higher
