### ISSUE TITLE
[Known Issue in 2.0.1] Forge causing chunk reset

### ISSUE THREAD

**Issue by ChespinBro** [LordDeatHunter/Alloy-Forgery#24]
I am currently running a server with friends that uses a modpack (Euphoric Curiosity) with this mod. Whenever the alloy forge block or multi structure (not sure which causes the issue) is placed it appears that the server has an issue with the chunk. As a result stopping and restarting the server results in the most recent available instance of the chunk to be loaded that did not include the forge resetting everything else in the chunk.

This could be a compatibility issue but I am not that great at testing myself so some people who are better at testing can probably test it themselves or give me some tips to try and test. I hope that this issue is not with the mod and rather with the pack as I think what this mod brings to the game is great. If I find any more details on this problem I will add it

In the images the alloy was built first then the world was closed and reopened.
![MC Euphoric Curiosity 8_7_2021 6_37_26 PM](https://user-images.githubusercontent.com/36646669/128615484-89a75b9a-cb93-40ed-9456-e3fe75637283.png)
![MC Euphoric Curiosity 8_7_2021 6_37_49 PM](https://user-images.githubusercontent.com/36646669/128615487-8ee4a5f6-66b4-4269-8005-612231366388.png)

**Comment by glisco03** [comment]
This is a know problem in 2.0.1 caused by me forgetting the register the controller block entity and subsequent insufficient testing. I highly apologize if any valuable chunks were lost because of this issue and recommend upgrading to 2.0.2 as quickly as you can. 
Cheers

**Comment by ChespinBro** [comment]
Thanks for letting me know :)
