### ISSUE TITLE
[2.0.3] Outputs cannot be pulled out of the forge using hoppers.

### ISSUE THREAD

**Issue by napmouse** [LordDeatHunter/Alloy-Forgery#27]
I've tried every single block on the bottom of the multiblock. None of them allow you to pull products out. This basically makes it entirely un-automatable.

**Comment by Noaaan** [comment]
This is likely a mod compat issue, as we are not able to reproduce with Alloy Forgery alone.

**Comment by Noaaan** [comment]
We have identified the issue as a compatability issue with Lithium. We are working on a fix.
