### ISSUE TITLE
Data Pack Inconsistency

### ISSUE THREAD

**Issue by ejektaflex** [LordDeatHunter/Alloy-Forgery#28]
Currently, 1 Iron Ore = 2 Iron Ingots. Same for Gold.

However, 1 Copper Ore = 3 Copper Ingots. 
Shouldn'1 1 Copper Ore also translate into 2 Copper Ingots?

**Comment by Noaaan** [comment]
No it should not. Copper ore in vanilla currently drops more than a single raw ore when mined, even without fortune. This is intentional behaviour.
