### ISSUE TITLE
Use AF to smelt other mod ignots

### ISSUE THREAD

**Issue by RotokEralil** [LordDeatHunter/Alloy-Forgery#32]
Hello! I am trying to add a new recipe to make an ingot from another mod I have installed (it is the Steel for Fabric by realguyman0).
I created a datapack using your mods namespace and his mod's namespace, tried each one at a time, and cant seem to get it to spit out a steel ingot! (I made the recipe require 1 iron ingot, 1 diorite, and 1 coal, to produce 1 steel ingot, and consume 50 fuel per tick.).
Any idea what I am doing wrong?
[Alloy_Forgery_with_steel.zip](https://github.com/LordDeatHunter/Alloy-Forgery/files/7886144/Alloy_Forgery_with_steel.zip)
[Steel-Forgery Mod.zip](https://github.com/LordDeatHunter/Alloy-Forgery/files/7886145/Steel-Forgery.Mod.zip)

**Comment by Noaaan** [comment]
Both of these datapacks seem correct. Could you check with Roughly Enough Items installed to see if the recipe shows up?

**Comment by RotokEralil** [comment]
I am an idiot; I set them to tier 2 (on purpose) and then kept trying to smelt it with a tier 1 smelter >.<
No issues now! Thank you for your response!
I will probably use the Steel-Forgery Mod version that uses steel namespace, as I do not know how to use datapacks to delete recipes, and I am going to replace his existing recipe to use the alloy forgery :)
