### ISSUE TITLE
[BUG] XP doesnt drop

### ISSUE THREAD

**Issue by ilkerbey-01** [LordDeatHunter/Alloy-Forgery#41]
When smelted in alloy forgery, ores dont drop xp, it should drop same xp if you smelted them in furnaces.

**Comment by Noaaan** [comment]
It is intentional that the Alloy Forge does not drop any experience when smelting ores, as you intentionally trade this off for a higher yield of ingots.

**Comment by ilkerbey-01** [comment]
would be nice if this was added as a config option
