### ISSUE TITLE
Creative tab crash

### ISSUE THREAD

**Issue by Niketats** [LordDeatHunter/Alloy-Forgery#42]
game crashes when opening creative tab page with alloy forgery category
mod version 2.0.11
[crash-2022-03-30_20.22.10-client.txt](https://github.com/LordDeatHunter/Alloy-Forgery/files/8382765/crash-2022-03-30_20.22.10-client.txt)

**Comment by Alec153** [comment]
same

**Comment by spoorn** [comment]
Will there be a release for this on curseforge?

**Comment by Noaaan** [comment]
Yes, it will likely be released sometime during this week

**Comment by Niketats** [comment]
mod version 2.0.12
still crash 
[crash-2022-04-15_17.24.26-client.txt](https://github.com/LordDeatHunter/Alloy-Forgery/files/8496447/crash-2022-04-15_17.24.26-client.txt)
