### ISSUE TITLE
Game Crashed While initializing

### ISSUE THREAD

**Issue by UpwardCabbage3** [LordDeatHunter/Alloy-Forgery#51]
I have been using this mod for a bit now but suddenly I can not open minecraft
[crash-2022-05-02_16.06.29-client.txt](https://github.com/LordDeatHunter/Alloy-Forgery/files/8606357/crash-2022-05-02_16.06.29-client.txt)

**Comment by Noaaan** [comment]
I do not think this issue is caused by Alloy Forgery, as the crashlog states that Limitless is failing to remove the anvil XP limit.  
Temporarily disabling Limitless should let your game run. 
I will look more into this issue tomorrow when I have more time.
