### ISSUE TITLE
Not accepting fuels(1.18.2)

### ISSUE THREAD

**Issue by Hydrophant** [LordDeatHunter/Alloy-Forgery#52]
I checked the files, and I don't think that a file dictating accepted fuels ever generated. I can't be sure though, as the directory to the fuel file shown on the wiki is incomplete and I can't find a path that looks like it.

**Comment by Noaaan** [comment]
The file isnt generated, it is part of the mods bundled data.
https://github.com/LordDeatHunter/Alloy-Forgery/tree/master/src/main/resources/data/alloy_forgery/alloy_forge_fuels

If the fuels fail to load they should throw errors in the log. 
If there are no errors, I recommend checking if you have an outdated version of More Bundles, as it causes some problems (see issue #45). 

If you do not use this mod, then there is likely some mod compatability issue. Please provide a full log so we can identify it.

**Comment by Hydrophant** [comment]
[latest.log](https://github.com/LordDeatHunter/Alloy-Forgery/files/8645829/latest.log)

**Comment by gliscowo** [comment]
Have you been able to figure something out regarding this problem?

**Comment by Hydrophant** [comment]
No

**Comment by gliscowo** [comment]
What modpack are you playing then? I would assume it's a custom one, since nobody else has ever encountered this specific issue

**Comment by Hydrophant** [comment]
It was Vanilla Hammers 3.3.0. Hammers 3.4.0 doesn't cause the problem.
