### ISSUE TITLE
EMI (REI alternative) Support

### ISSUE THREAD

**Issue by ZekeSmith** [LordDeatHunter/Alloy-Forgery#55]
EMI Is an alternative to the REI recipe browser it has a more modern UI is available on modrinth, features a recipe tree and other qol changes.

https://modrinth.com/mod/emi

Currently the recipes for basic items are viewable however alloy forging is not shown. I don't know if this is possible to implement with EMI however if possible it would be very useful, especially for Modrinth modpack developers.

_Basic crafting works_
![image](https://user-images.githubusercontent.com/81902668/173016221-b16c0793-2ea1-421a-ab5d-f48a7267ad5d.png)

_Metal that uses alloy forgery not showing forging recipe_
![image](https://user-images.githubusercontent.com/81902668/173016306-50145c1a-dd96-47c9-8167-6c30486d067b.png)

**Comment by gliscowo** [comment]
Given that there is currently no real-world advantage for us to support EMI + the fact that we don't want to maintain two different recipe viewer implementations, I'll go ahead and close this as wontfix for now. Not saying it will never happen, but for the time being it's not planned
Cheers

**Comment by fzzyhmstrs** [comment]
Would you accept a PR for this plugin? EMI's used/desired to be used in several modpacks that use forgery, including at least a couple quite popular ones; the plugin would make forgery more accessible in those packs. Also seems like commits to your REI plugin are months and months apart, so I'd think maintenance would be pretty time-light. 

Let me know and I can whip one up for you if you're down! Totally ok if not.

**Comment by Noaaan** [comment]
Yea

**Comment by KIRUYXAN** [comment]
But it works with fewer mods
