### ISSUE TITLE
Unable to stack inside Alloy Forge with automation.

### ISSUE THREAD

**Issue by ardissaps** [LordDeatHunter/Alloy-Forgery#59]
The item keep inserting on another slot instead of stacking in one slot, thus unable to make alloy that need combination : (1.18.2)
![image](https://user-images.githubusercontent.com/82106625/177126603-6ba756a4-669c-4f04-88df-841baedfdefb.png)
I hope it can be fixed soon.

**Comment by Noaaan** [comment]
You should be able to automate the Forge using redstone with your pipes, please see [this section of the AF wiki.](https://github.com/LordDeatHunter/Alloy-Forgery/wiki/Building-a-Forge#automation)

**Comment by Noaaan** [comment]
Please also note that in 2.0.13 alloying recipes require exact stack inputs, meaning bronze for which needs 2 pieces copper and one piece tin, would fill 3 slots (which is why items are inserted into the Forge this way)

**Comment by ardissaps** [comment]
Okay, I'll try tommorow! :)

**Comment by ardissaps** [comment]
Ok, it actually not a big deal, just suggestion maybe can let it left 1 material unprocessed that work like filter so incoming item only fill the stack that are there. Anyway, thanks for the good mod, I currently use Creaete Basin to process MythicMetal alloy.
