### ISSUE TITLE
Lava Bar on the GUI does not render correctly

### ISSUE THREAD

**Issue by ardissaps** [LordDeatHunter/Alloy-Forgery#65]
![image](https://user-images.githubusercontent.com/82106625/181149165-37c7b099-83d9-46da-99b9-c4ede22de9c9.png)
I filled it with Lava from [Create](https://modrinth.com/mod/create-fabric)'s Fluid Tanks with [Modern Dynamic](https://modrinth.com/mod/modern-dynamics)'s Pipe
(1.18.2)

**Comment by Noaaan** [comment]
This issue should already be fixed as of [Alloy Forgery 2.0.15](https://github.com/LordDeatHunter/Alloy-Forgery/releases/tag/2.0.15%2B1.19). Please use this version instead.

**Comment by ardissaps** [comment]
> This issue should already be fixed as of [Alloy Forgery 2.0.15](https://github.com/LordDeatHunter/Alloy-Forgery/releases/tag/2.0.15%2B1.19). Please use this version instead.

Thank you, will it be ported to 1.18.2? (my 1.19 pack isn't finished)

**Comment by gliscowo** [comment]
Since this is a minor visual glitch that does not affect gameplay in any way and the 1.18 support cycle has ended some time ago, we won't backport this patch
Cheers
