### ISSUE TITLE
Strange crash

### ISSUE THREAD

**Issue by Sunconure11** [LordDeatHunter/Alloy-Forgery#69]
https://pastebin.com/bVLTwiG8

**Comment by Noaaan** [comment]
See https://github.com/devs-immortal/Incubus-Core/pull/15 for context. 
This is a known issue between Alloy Forgery and Incubus Core. It has already been fixed on their side, although it has not been released yet. 
You can grab a working build of it from their GitHub actions: https://github.com/devs-immortal/Incubus-Core/actions

**Comment by Sunconure11** [comment]
In this case, it is a mod using it as an embedded library. I have since reported it.
