### ISSUE TITLE
Lil Forge error.

### ISSUE THREAD

**Issue by RDKRACZ** [LordDeatHunter/Alloy-Forgery#7]
You can build this
![image](https://user-images.githubusercontent.com/43277609/110215259-072e9c00-7ea9-11eb-95d7-6edd5c9d3bf4.png)

and then do this and it will still work (yes it is empty inside)
![image](https://user-images.githubusercontent.com/43277609/110215283-262d2e00-7ea9-11eb-871c-a8975600be4c.png)

**Comment by RDKRACZ** [comment]
You should allow building this with obsidian too.

**Comment by Noaaan** [comment]
This is actually intended! 
The reasoning is so that you could expand upon it. For example you could use a trapdoor as a hatch for the smoke.
