### ISSUE TITLE
Causes crash on launch with Spectrum mod, on Fabric 1.19.2

### ISSUE THREAD

**Issue by TalEdd** [LordDeatHunter/Alloy-Forgery#71]
[crash-2022-09-30_00.12.45-client.txt](https://github.com/LordDeatHunter/Alloy-Forgery/files/9676837/crash-2022-09-30_00.12.45-client.txt)

Mod in question: [Spectrum](https://www.curseforge.com/minecraft/mc-mods/spectrum)

**Comment by gliscowo** [comment]
Duplicate of #69

**Comment by TalEdd** [comment]
Noted, thank you! Managed to get it running now.
