### ISSUE TITLE
no REI compat for fabric

### ISSUE THREAD

**Issue by DragonInsight** [LordDeatHunter/Alloy-Forgery#75]
when i use the latest version with rei and mythic metals, no recipes appear in rei for the metals.

**Comment by gliscowo** [comment]
There is a lot of missing information here. 
 - Are you using a modpack? If yes, which one?
 - Are you sure you have installed REI and JEI? 
 - Are there any errors in your log?
 
In general, please send us your `latest.log` so we can have a stab at finding the problem
Cheers

**Comment by Noaaan** [comment]
Considering REI works fine in our testing, and the lack of a response, I see no reason to keep this issue open.
If you are still experiencing issues with REI, please provide more information as described above.
