### ISSUE TITLE
Lava buckets not leaving behind bucket

### ISSUE THREAD

**Issue by CreepTron365** [LordDeatHunter/Alloy-Forgery#77]
When Lava Buckets are used in forge controllers as fuel, they consume the whole bucket instead of leaving behind the bucket like the furnaces

**Comment by Noaaan** [comment]
Hi, can you provide more details?
For example what version of the mod are you using, and are you using any other mods?

**Comment by CreepTron365** [comment]
Hi Noaaan, I have been trying to reproduce the bug but it doesn't seem to reoccur. My server has been a bit glitchy and have been trying to make it more stable, I highly apologise for the inconvenience. I will report again if I am able to reproduce it.
