### ISSUE TITLE
[Crash on Boot] Crashes on version 2.0.16, works on 2.0.13

### ISSUE THREAD

**Issue by dhasial** [LordDeatHunter/Alloy-Forgery#81]
Crash log: https://mclo.gs/OqbeTRR
Modlist: https://mclo.gs/khvijob

**Comment by Noaaan** [comment]
Are you sure this is being caused by Alloy Forgery? 
A Feature Order Cycle crash happens during worldgen, which is something we do not touch at all.

**Comment by Dragon-Seeker** [comment]
> Crash log: https://mclo.gs/OqbeTRR Modlist: https://mclo.gs/khvijob

Your Crash log doesn't even have Alloy Forgery, so How is it our fault?
