### ISSUE TITLE
Mixin transformation of wraith.alloyforgery.block.ForgeControllerBlockEntity failed

### ISSUE THREAD

**Issue by DemonMartin** [LordDeatHunter/Alloy-Forgery#82]
Server Crash: https://mclo.gs/tp9LS7P (Not actually a server)
Client Crash: https://mclo.gs/v47pDT4 (tho, not really important)

Worked fine on v2.0.13+1.18

Stopped working on v2.0.16+1.18.2

**Comment by Dragon-Seeker** [comment]
This is an issue with [Megane](https://github.com/badasintended/megane) and their compact for alloy forgery with the 1.18.2 version. Such needs to be fixed on their side with there accessor mixin.

**Comment by DemonMartin** [comment]
Ah, okay! Do I need to report that to them or something like that?

**Comment by Dragon-Seeker** [comment]
Yes

**Comment by DemonMartin** [comment]
Reported [#55](https://github.com/badasintended/megane/issues/55) :)

**Comment by Noaaan** [comment]
Fixed in the latest release of Megane, thanks for reporting
