### ISSUE TITLE
Crash game when i try to use forge(minecraft 1.19.2 fabric)

### ISSUE THREAD

**Issue by OneDayGame435** [LordDeatHunter/Alloy-Forgery#91]
When i click rmb on everything forge with mod alloy forgery, game is crash. Pls help me with this problem(((  (Sorry for my eng)

**Comment by OneDayGame435** [comment]
[crash-2022-12-23_21.12.16-client.txt](https://github.com/wisp-forest/alloy-forgery/files/10294966/crash-2022-12-23_21.12.16-client.txt)

**Comment by BasiqueEvangelist** [comment]
Duplicate of #80
[Charm Fixer](modrinth.com/mod/charm-fixer) mitigates this issue, so you should probably install it

**Comment by OneDayGame435** [comment]
Thx!!!!!!!
