### ISSUE TITLE
Minecraft crash when play

### ISSUE THREAD

**Issue by OneDayGame435** [LordDeatHunter/Alloy-Forgery#92]
[crash-2022-12-25_00.48.48-server.txt](https://github.com/wisp-forest/alloy-forgery/files/10298840/crash-2022-12-25_00.48.48-server.txt)
Pls help <3

**Comment by Noaaan** [comment]
This crash explicitly mentions Gobber. Are you sure this is related to Alloy Forgery?

**Comment by BasiqueEvangelist** [comment]
Are you using the latest Gobber? This is already fixed in the repo, and a release with the fix is out
https://www.curseforge.com/minecraft/mc-mods/gobber-fabric/files/4086199 should be what you need

**Comment by gliscowo** [comment]
As the problem is not caused by Alloy Forgery, I'll go ahead and close this issue
Cheers
