### ISSUE TITLE
mod version 2.0.15 and 2.0.16 crash when near alloy forge

### ISSUE THREAD

**Issue by m0thknight** [LordDeatHunter/Alloy-Forgery#93]
Unclear what is causing this. However I will say that the only reason I am using version 2.0.15 is because I couldn't use 2.0.17 with charm. 
https://crashy.net/dRpSmNthpCQI3PfS4Jk2 crash on mod version 2.0.15
https://crashy.net/XGztyBKev0aLMQN6Qlwa same crash on mod version 2.0.16
[crash-2023-02-01_20.42.23-server.txt](https://github.com/wisp-forest/alloy-forgery/files/10564986/crash-2023-02-01_20.42.23-server.txt)
[crash-2023-02-01_21.00.41-server.txt](https://github.com/wisp-forest/alloy-forgery/files/10564987/crash-2023-02-01_21.00.41-server.txt)

**Comment by Noaaan** [comment]
Use latest combined with Charm Fixer. See this comment: https://github.com/wisp-forest/alloy-forgery/issues/80#issuecomment-1312286257

**Comment by gliscowo** [comment]
While this is a known problem, it has been fixed in the newer version. Do as @Noaaan suggested and use the latest mod version combined with [Charm Fixer](https://modrinth.com/mod/charm-fixer)

Cheers
