### ISSUE TITLE
[suggestion] Regarding raw item feeding

### ISSUE THREAD

**Issue by NyarlathotepZERO** [LordDeatHunter/Alloy-Forgery#94]
Feeding single items into the furnace can be difficult due to the multiple slots for alloying, this can be circumvented by building a separate furnace for each type of metal, but could something be implemented where the user is able to somehow lock off all the extra alloying slots thus only allowing a single type of ore to feed in at a time ?

**Comment by Noaaan** [comment]
I recommend checking out this section on the Alloy Forgery wiki: https://github.com/wisp-forest/alloy-forgery/wiki/Building-a-Forge#automation
This is not something we would want to implement, as it would make the Forge GUI more complex. Considering the Forge is able to produce redstone signals when processing recipes, you should be able to simply lock your item input during crafting. This should let you automate it nicely.

**Comment by NyarlathotepZERO** [comment]
I can appreciate that it *could* make the GUI more complex depending on how it was implemented, but *would* is open to conjecture. Something as clear and simple as when you click on one of the many empty boxes, it toggles a red cross over it or greys the box out (or even both). This would simply and clearly signal that the box; after being clicked on is now unavailable.

If a red cross or greyed out box is not clear enough, then I'm sure adding a tooltip to this state when mousing over the box would bring anybody who was uncertain; into pretty clear understanding of what their click just changed.

**Comment by gliscowo** [comment]
Let's approach this from a different angle - namely, we specifically *want* automating the Alloy Forge to be a bit of a challenge that warrants some thought. As Noaaan mentioned in his comment above, you can already do this by working with the redstone output provided by the Controller. Implementing functionality to make this trivial would be going against this goal. As such, I'll be closing this issue

We do plan to potentially revisit Forge automation at some point in the future with a more well-designed system, but that's still up for debate

Cheers
