### ISSUE TITLE
Stacker issue with lava bucket

### ISSUE THREAD

**Issue by gamerpotion** [LordDeatHunter/Alloy-Forgery#96]
Hi, a user from my pack commented on an issue when using stacked lava buckets and it consumes the whole stack but only sees it as x1.

Please see more info here - https://github.com/gamerpotion/DarkRPG/issues/58
There is a video link on there as well from the user.

**Comment by Dragon-Seeker** [comment]
From what I understand is there is no Vanilla way to stack Lava buckets... They could instead just use a tank that inputs lava into the Forge unless that pack has no tanks or pipes to transfer such.

**Comment by Dragon-Seeker** [comment]
@Noaaan @gliscowo Thoughts?

**Comment by Noaaan** [comment]
Thanks for letting us know. I have implemented a fix for this which should prevent similar issues from happening.
