### ISSUE TITLE
Update Please [1.19.3] EMI Merge

### ISSUE THREAD

**Issue by gamerpotion** [LordDeatHunter/Alloy-Forgery#97]
Please could https://github.com/wisp-forest/alloy-forgery/pull/87 be updated so we can start using EMI ?   fzzyhmstrs  has informed me its sitting somewhere but not pushed

Im updated DarkRPG to 1.19.3 soon, so would be nice to have this thanks

**Comment by Noaaan** [comment]
It is pushed, it was simply not released. I have just gone ahead and made a new release which includes this.
